### ISSUE TITLE
Installation Hepl

### ISSUE THREAD

**Issue by Manish2035** [g-stefan/totalbattle.bot#2]
Hi, 
I need help with the installation of the software.
all i did was download it.
I could not find any video or installation guide for this one.
Could you please help.
Regards,

**Comment by g-stefan** [comment]
Hello! Just extract the archive and after just run "run-bot.cmd", the software is portable.

I have made another software, commercial one, you can find it at [total-battle-assistant.com](https://total-battle-assistant.com/).
Smaller and with some extra options.
